version: '3.3'

services:

  app:

    build:
      context: .
      dockerfile: Dockerfile
    image: php-continous:latest
    container_name: php-continous
    ports:
      - 8080:80
    working_dir: /var/www
    volumes:
      - ./src:/var/www/app
      - ./vendor:/var/www/vendor
      - ./composer.json:/var/www/composer.json
    restart: unless-stopped