version: '3.3'

services:

  app:

    build:
      context: .
      dockerfile: Dockerfile.development
    container_name: php-continous
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 remote_autostart=1
    ports:
      - 8080:8080
    volumes:
      - ./:/opt/application
    restart: unless-stopped